In [1]:
l = [1,2,3,4,5,6,7,8,9]

In [2]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = np.array([12,4,55,6322300,454.32])

In [8]:
b

array([1.2000e+01, 4.0000e+00, 5.5000e+01, 6.3223e+06, 4.5432e+02])

In [9]:
print(b)

[1.2000e+01 4.0000e+00 5.5000e+01 6.3223e+06 4.5432e+02]


In [10]:
l.pop()

9

In [11]:
l

[1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
a.mean()

5.0

In [13]:
a[::2]

array([1, 3, 5, 7, 9])

In [14]:
a[2::2]

array([3, 5, 7, 9])

In [15]:
a[1]

2

In [16]:
a[2:4]

array([3, 4])

In [17]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = a[2:4]

In [19]:
b[:] = 111

In [20]:
a

array([  1,   2, 111, 111,   5,   6,   7,   8,   9])

In [21]:
c = a.copy()

In [22]:
c

array([  1,   2, 111, 111,   5,   6,   7,   8,   9])

In [23]:
c[0]=0

In [24]:
c

array([  0,   2, 111, 111,   5,   6,   7,   8,   9])

In [25]:
a

array([  1,   2, 111, 111,   5,   6,   7,   8,   9])